#!/bin/bash
# Fetch the Nowhere default apps (DIA-20260617-06) from F-Droid at the versions pinned in
# default-apps.manifest. The APKs are gitignored (not committed; ~277 MB), so run this ONCE on a fresh
# tree before `m systemimage` -- the Android.bp android_app_import modules expect prebuilts/<Name>.apk.
# Idempotent: an APK already present with the pinned SHA256 is left alone. Verifies SHA256 after download
# (a mismatch -> hard fail, so a tampered/rotated mirror can't slip in a different binary).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
MANIFEST="$HERE/default-apps.manifest"
[ -f "$MANIFEST" ] || { echo "no manifest at $MANIFEST" >&2; exit 1; }

sha_of() { sha256sum "$1" | cut -d' ' -f1; }

while read -r name pkg vc sha _rest; do
  case "${name:-}" in ""|\#*) continue;; esac
  out="$HERE/$name.apk"
  if [ -f "$out" ] && [ "$(sha_of "$out")" = "$sha" ]; then
    echo "ok   $name (cached, sha ok)"
    continue
  fi
  url="https://f-droid.org/repo/${pkg}_${vc}.apk"
  echo "get  $name  <-  $url"
  curl -fsSL --retry 3 -o "$out" "$url"
  got="$(sha_of "$out")"
  if [ "$got" != "$sha" ]; then
    echo "SHA256 MISMATCH for $name: got $got, want $sha" >&2
    rm -f "$out"
    exit 1
  fi
  echo "ok   $name (downloaded, sha ok)"
done < "$MANIFEST"

echo "all default apps present + verified in $HERE"

# --- JNI libs (DIA-20260618-01) -------------------------------------------------------------------
# F-Droid ships these apps with compressed native libs + extractNativeLibs=true (libs are meant to be
# unpacked at install). A verbatim (preprocessed) system app never unpacks them, so dlopen fails at
# launch (Fennec/OrganicMaps/AntennaPod crash; NewPipe's lazy load would too). Re-zipping the APK to
# uncompress the libs would break its F-Droid v2/v3 signature -- so instead we extract each APK's arm64
# .so here and copy them into the app's /product lib dir (where the loader looks for a system app),
# leaving the APK byte-identical. Emit a PRODUCT_COPY_FILES fragment that diaspore.mk -includes.
# FP3 runs these apps 64-bit, so only arm64-v8a libs are needed (dir name on device is "arm64").
# Edition-aware: $HERE is .../vendor/<edition>/prebuilts, so the build-relative copy path is
# vendor/<edition>/prebuilts -- derive it instead of hardcoding diaspore (so endospore reuses this).
VENDOR_REL="vendor/$(basename "$(dirname "$HERE")")/prebuilts"
# Overridable so an edition can narrow the set (e.g. Endospore drops Fennec -> uses Vanadium instead).
JNI_APPS="${JNI_APPS:-OrganicMaps Fennec NewPipe AntennaPod}"
FRAG="$HERE/default-apps-jni.mk"
{
  echo "# AUTO-GENERATED by fetch-default-apps.sh -- do not edit, do not commit (.gitignored)."
  echo "# Per-app arm64 JNI .so extracted from the F-Droid APKs (compressed, extractNativeLibs=true) and"
  echo "# copied into each app's /product lib dir so the loader resolves them. Regenerated on every fetch."
} > "$FRAG"
for name in $JNI_APPS; do
  apk="$HERE/$name.apk"
  [ -f "$apk" ] || { echo "skip jni: $name.apk missing" >&2; continue; }
  dest="$HERE/jni/$name/arm64"
  rm -rf "$HERE/jni/$name"
  mkdir -p "$dest"
  unzip -j -o "$apk" 'lib/arm64-v8a/*.so' -d "$dest" >/dev/null 2>&1 || true
  n=0
  for so in "$dest"/*.so; do
    [ -f "$so" ] || continue
    base="$(basename "$so")"
    echo "PRODUCT_COPY_FILES += $VENDOR_REL/jni/$name/arm64/$base:\$(TARGET_COPY_OUT_PRODUCT)/app/$name/lib/arm64/$base" >> "$FRAG"
    n=$((n+1))
  done
  echo "jni  $name  ($n arm64 .so)"
done
echo "wrote $FRAG"
